# fly.toml file generated for tailscale-dev on 2023-01-16T20:19:51-08:00

app = "tailscale-dev"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "3000"

[experimental]
  auto_rollback = true

[mounts]
  source="next_cache"
  destination="/app/.next/cache"

[deploy]
  strategy = "bluegreen"

[[services]]
  http_checks = []
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 50
    soft_limit = 40
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
