import NextImage, { ImageProps } from 'next/image';

interface HeroImage extends ImageProps {
  desc: string;
  generator?: string;
}

export function HeroImage({ src, desc, width, height, generator }: HeroImage) {
  return (
    <figure className="hero mx-1 my-6">
      <NextImage src={src} alt={desc} width={width} height={height} />
      {generator !== undefined ? (
        <figcaption className="mx-2 my-1 text-center text-gray-600 dark:text-gray-400">
          Image generated by {generator}, prompt: {desc}
        </figcaption>
      ) : (
        <figcaption className="mx-2 my-1 text-center text-gray-600 dark:text-gray-400">
          {desc}
        </figcaption>
      )}
      <meta property="og:image" content={`${src}`} />
    </figure>
  );
}
