name: Linkchecker
on:
  pull_request:
    paths:
      - .github/workflows/linkchecker.yml
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
jobs:
  linkchecker:
    runs-on: ubuntu-latest
    steps:
      - name: Install linkchecker
        run: >
          sudo apt-get update && sudo apt-get install -y python3-pip && pip3
          install linkchecker
      - name: Run linkchecker
        run: |
          linkchecker --ignore-url=^mailto: https://tailscale.dev
